baseURL = 'https://seanome.org/'
languageCode = 'en-us'
title = 'Seanome'
theme = 'hermit-v2'
[params]
  homeSubtitle = "Unlocking cures from ocean biodiversity with open genomics tools"
  homeSubtitlePrinter = true
  [params.contact]
    email = 'info@seanome.org'
  custom_css = ["scss/userstyles.scss"]
  google_fonts = [
    ["Poppins", "400, 700"],
  ]
  heading_font = "Poppins"
  body_font = "Poppins"


[params.author]
  name = "Seanome"

features = [
  "single column",
  "social icons",
  "google analytics",
  "customizable"
]
