baseURL = 'https://seanome.org/'
languageCode = 'en-us'
title = 'Seanome'
theme = 'hermit-v2'

[params]
homeSubtitle = "Unlocking breakthroughs from ocean biodiversity"
homeSubtitlePrinter = true

dateformShort = "Jan 2, 2006"
dateformLong = "Monday, January 2, 2006"
dateformShortWithTime = "Jan 2, 2006 3:04 PM"

code_copy_button = true
google_fonts = [
  [
    "Cinzel Decorative",
    "300, 400, 700",
  ],
  [
    "Fira Mono",
    "200, 300, 400, 700",
  ],
  [
    "Fira Sans",

    "200, 300, 400, 700",

  ],
]

custom_css = ["css/custom.css"]


[params.contact]
email = 'info@seanome.org'


[[params.socialLinks]]
name = 'github'
url = 'https://github.com/seanome'

[[params.socialLinks]]
name = 'x'
url = 'https://x.com/SeanomeSF'

[[params.socialLinks]]
name = 'bluesky'
url = 'https://bsky.app/profile/seanome.bsky.social'

[[params.socialLinks]]
name = 'linkedin'
url = 'https://www.linkedin.com/company/seanome/'


[[params.socialLinks]]
name = 'substack'
url = 'https://seanome.substack.com/'


# [[params.socialLinks]]
# name = 'wavebywave-substack'
# url = 'https://wavebywave.substack.com/'


[params.author]
name = "Seanome"

features = ["single column", "social icons", "google analytics", "customizable"]


[menu]

[[menu.main]]
name = "Substack Blog"
url = "https://seanome.substack.com/"
weight = 10

[[menu.main]]
name = "About"
url = "about/"
weight = 20
